OrdererOrgs:
  - Name: Orderer
    Domain: orderernode.com
    CA: 
      Country: US
      Province: California
      Locality: San Francisco
    Specs:
      - Hostname: orderer
PeerOrgs:
  - Name: Org1
    Domain: org1.peernode.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1
  - Name: Org2
    Domain: org2.peernode.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1
